/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  ICircuitBreaker,
  ICircuitBreakerInterface,
} from '../../SentinelMonitor.sol/ICircuitBreaker.js';

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'chainId',
        type: 'uint256',
      },
    ],
    name: 'getCircuitStats',
    outputs: [
      {
        internalType: 'uint8',
        name: 'state',
        type: 'uint8',
      },
      {
        internalType: 'uint256',
        name: 'failures',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'lastFailure',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'successCount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isShutdown',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ICircuitBreaker__factory {
  static readonly abi = _abi;
  static createInterface(): ICircuitBreakerInterface {
    return new Interface(_abi) as ICircuitBreakerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICircuitBreaker {
    return new Contract(address, _abi, runner) as unknown as ICircuitBreaker;
  }
}
