/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  ISentinelInterceptor,
  ISentinelInterceptorInterface,
} from '../../SentinelMonitor.sol/ISentinelInterceptor.js';

const _abi = [
  {
    inputs: [],
    name: 'getAnomalyStats',
    outputs: [
      {
        internalType: 'uint256',
        name: 'totalCount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'lastBlock',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'consecutive',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'currentBlockFrequency',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ISentinelInterceptor__factory {
  static readonly abi = _abi;
  static createInterface(): ISentinelInterceptorInterface {
    return new Interface(_abi) as ISentinelInterceptorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISentinelInterceptor {
    return new Contract(address, _abi, runner) as unknown as ISentinelInterceptor;
  }
}
