[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000
via_ir = false
bytecode_hash = "none"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solidity-examples/=lib/solidity-examples/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/"
]
