[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@layerzerolabs/solidity-examples/=lib/solidity-examples/",
    "solidity-examples/=lib/solidity-examples/"
]

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
sort_imports = true
wrap_comments = true
