/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export { ERC20Mock__factory } from './ERC20Mock__factory.js';
export { ERC20VotesMock__factory } from './ERC20VotesMock__factory.js';
