/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AetheronBridgeInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "MAX_CHAIN_VOLUME" | "MAX_TRANSFERS_PER_USER" | "OPERATOR_ROLE" | "RELAYER_ROLE" | "bridgeFee" | "bridgeTokens" | "canProcessTransfer" | "chainLimits" | "chainTransferVolume" | "emergencyPause" | "emergencyUnpause" | "getBridgeStats" | "getRoleAdmin" | "grantRole" | "hasRole" | "initializeBridge" | "owner" | "paused" | "renounceOwnership" | "renounceRole" | "revokeRole" | "setBridgeFee" | "setChainLimit" | "setRelayer" | "setTokenSupport" | "supportedTokenCount" | "supportedTokens" | "supportsInterface" | "totalTransferCount" | "totalValueLocked" | "transferOwnership" | "transfers" | "unbridgeTokens" | "userTransferCount" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BridgeInitialized" | "EmergencyPaused" | "EmergencyUnpaused" | "OwnershipTransferred" | "Paused" | "RelayerUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TokenSupportUpdated" | "TokensBridged" | "TokensUnbridged" | "TransferCompleted" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CHAIN_VOLUME', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TRANSFERS_PER_USER', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'RELAYER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'bridgeFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'bridgeTokens', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'canProcessTransfer', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'chainLimits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'chainTransferVolume', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyPause', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyUnpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBridgeStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initializeBridge', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setBridgeFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setChainLimit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRelayer', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTokenSupport', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportedTokenCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportedTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalTransferCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalValueLocked', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transfers', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unbridgeTokens', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'userTransferCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CHAIN_VOLUME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TRANSFERS_PER_USER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RELAYER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bridgeFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bridgeTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canProcessTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainTransferVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyUnpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBridgeStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeBridge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBridgeFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setChainLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenSupport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedTokenCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTransferCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalValueLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbridgeTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userTransferCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace BridgeInitializedEvent {
      export type InputTuple = [token: AddressLike, bridge: AddressLike, initialSupply: BigNumberish];
      export type OutputTuple = [token: string, bridge: string, initialSupply: bigint];
      export interface OutputObject {token: string, bridge: string, initialSupply: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyPausedEvent {
      export type InputTuple = [pauser: AddressLike];
      export type OutputTuple = [pauser: string];
      export interface OutputObject {pauser: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnpausedEvent {
      export type InputTuple = [unpauser: AddressLike];
      export type OutputTuple = [unpauser: string];
      export interface OutputObject {unpauser: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RelayerUpdatedEvent {
      export type InputTuple = [relayer: AddressLike, authorized: boolean];
      export type OutputTuple = [relayer: string, authorized: boolean];
      export interface OutputObject {relayer: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenSupportUpdatedEvent {
      export type InputTuple = [token: AddressLike, supported: boolean];
      export type OutputTuple = [token: string, supported: boolean];
      export interface OutputObject {token: string, supported: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensBridgedEvent {
      export type InputTuple = [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, chainId: BigNumberish, tokenAddress: AddressLike, transferId: BytesLike];
      export type OutputTuple = [sender: string, recipient: string, amount: bigint, chainId: bigint, tokenAddress: string, transferId: string];
      export interface OutputObject {sender: string, recipient: string, amount: bigint, chainId: bigint, tokenAddress: string, transferId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensUnbridgedEvent {
      export type InputTuple = [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, transferId: BytesLike];
      export type OutputTuple = [sender: string, recipient: string, amount: bigint, transferId: string];
      export interface OutputObject {sender: string, recipient: string, amount: bigint, transferId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferCompletedEvent {
      export type InputTuple = [transferId: BytesLike];
      export type OutputTuple = [transferId: string];
      export interface OutputObject {transferId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AetheronBridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): AetheronBridge;
    waitForDeployment(): Promise<this>;

    interface: AetheronBridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_CHAIN_VOLUME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_TRANSFERS_PER_USER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    RELAYER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    bridgeFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bridgeTokens: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, chainId: BigNumberish, tokenAddress: AddressLike, ],
      [void],
      'payable'
    >
    

    
    canProcessTransfer: TypedContractMethod<
      [transferId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    chainLimits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    chainTransferVolume: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    emergencyPause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    emergencyUnpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getBridgeStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {tvl: bigint, fee: bigint, tokenCount: bigint }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initializeBridge: TypedContractMethod<
      [tokenAddress: AddressLike, initialSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBridgeFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setChainLimit: TypedContractMethod<
      [chainId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRelayer: TypedContractMethod<
      [relayer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenSupport: TypedContractMethod<
      [tokenAddress: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportedTokenCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportedTokens: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalTransferCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalValueLocked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transfers: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, string, boolean] & {sender: string, recipient: string, amount: bigint, chainId: bigint, tokenAddress: string, transferId: string, completed: boolean }],
      'view'
    >
    

    
    unbridgeTokens: TypedContractMethod<
      [transferId: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    userTransferCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CHAIN_VOLUME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TRANSFERS_PER_USER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'RELAYER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'bridgeFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bridgeTokens'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, chainId: BigNumberish, tokenAddress: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'canProcessTransfer'): TypedContractMethod<
      [transferId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'chainLimits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'chainTransferVolume'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyPause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyUnpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBridgeStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {tvl: bigint, fee: bigint, tokenCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initializeBridge'): TypedContractMethod<
      [tokenAddress: AddressLike, initialSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBridgeFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setChainLimit'): TypedContractMethod<
      [chainId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRelayer'): TypedContractMethod<
      [relayer: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenSupport'): TypedContractMethod<
      [tokenAddress: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportedTokenCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportedTokens'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalTransferCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalValueLocked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transfers'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, string, boolean] & {sender: string, recipient: string, amount: bigint, chainId: bigint, tokenAddress: string, transferId: string, completed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'unbridgeTokens'): TypedContractMethod<
      [transferId: BytesLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userTransferCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BridgeInitialized'): TypedContractEvent<BridgeInitializedEvent.InputTuple, BridgeInitializedEvent.OutputTuple, BridgeInitializedEvent.OutputObject>;
getEvent(key: 'EmergencyPaused'): TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
getEvent(key: 'EmergencyUnpaused'): TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RelayerUpdated'): TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TokenSupportUpdated'): TypedContractEvent<TokenSupportUpdatedEvent.InputTuple, TokenSupportUpdatedEvent.OutputTuple, TokenSupportUpdatedEvent.OutputObject>;
getEvent(key: 'TokensBridged'): TypedContractEvent<TokensBridgedEvent.InputTuple, TokensBridgedEvent.OutputTuple, TokensBridgedEvent.OutputObject>;
getEvent(key: 'TokensUnbridged'): TypedContractEvent<TokensUnbridgedEvent.InputTuple, TokensUnbridgedEvent.OutputTuple, TokensUnbridgedEvent.OutputObject>;
getEvent(key: 'TransferCompleted'): TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'BridgeInitialized(address,address,uint256)': TypedContractEvent<BridgeInitializedEvent.InputTuple, BridgeInitializedEvent.OutputTuple, BridgeInitializedEvent.OutputObject>;
      BridgeInitialized: TypedContractEvent<BridgeInitializedEvent.InputTuple, BridgeInitializedEvent.OutputTuple, BridgeInitializedEvent.OutputObject>;
    

      'EmergencyPaused(address)': TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
      EmergencyPaused: TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
    

      'EmergencyUnpaused(address)': TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
      EmergencyUnpaused: TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RelayerUpdated(address,bool)': TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
      RelayerUpdated: TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TokenSupportUpdated(address,bool)': TypedContractEvent<TokenSupportUpdatedEvent.InputTuple, TokenSupportUpdatedEvent.OutputTuple, TokenSupportUpdatedEvent.OutputObject>;
      TokenSupportUpdated: TypedContractEvent<TokenSupportUpdatedEvent.InputTuple, TokenSupportUpdatedEvent.OutputTuple, TokenSupportUpdatedEvent.OutputObject>;
    

      'TokensBridged(address,address,uint256,uint256,address,bytes32)': TypedContractEvent<TokensBridgedEvent.InputTuple, TokensBridgedEvent.OutputTuple, TokensBridgedEvent.OutputObject>;
      TokensBridged: TypedContractEvent<TokensBridgedEvent.InputTuple, TokensBridgedEvent.OutputTuple, TokensBridgedEvent.OutputObject>;
    

      'TokensUnbridged(address,address,uint256,bytes32)': TypedContractEvent<TokensUnbridgedEvent.InputTuple, TokensUnbridgedEvent.OutputTuple, TokensUnbridgedEvent.OutputObject>;
      TokensUnbridged: TypedContractEvent<TokensUnbridgedEvent.InputTuple, TokensUnbridgedEvent.OutputTuple, TokensUnbridgedEvent.OutputObject>;
    

      'TransferCompleted(bytes32)': TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
      TransferCompleted: TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }