/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export interface CircuitBreakerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'DEFAULT_ADMIN_ROLE'
      | 'FAILURE_THRESHOLD'
      | 'FAILURE_WINDOW'
      | 'MAX_FAILURE_HISTORY'
      | 'MONITOR_ROLE'
      | 'OPERATOR_ROLE'
      | 'RECOVERY_ATTEMPTS'
      | 'TIMEOUT_PERIOD'
      | 'circuitStates'
      | 'closeCircuit'
      | 'emergencyPause'
      | 'emergencyUnpause'
      | 'failureCounts'
      | 'failureHistory'
      | 'getCircuitStats'
      | 'getFailureHistory'
      | 'getRoleAdmin'
      | 'grantRole'
      | 'halfOpenSuccessCount'
      | 'hasRole'
      | 'isCircuitClosed'
      | 'lastFailureTime'
      | 'lastSuccessTime'
      | 'openCircuit'
      | 'owner'
      | 'paused'
      | 'permanentShutdown'
      | 'recordFailure'
      | 'recordSuccess'
      | 'renounceOwnership'
      | 'renounceRole'
      | 'revokeRole'
      | 'supportsInterface'
      | 'transferOwnership'
      | 'triggerPermanentShutdown'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'CircuitClosed'
      | 'CircuitHalfOpened'
      | 'CircuitOpened'
      | 'EmergencyPaused'
      | 'EmergencyUnpaused'
      | 'FailureRecorded'
      | 'OwnershipTransferred'
      | 'Paused'
      | 'RoleAdminChanged'
      | 'RoleGranted'
      | 'RoleRevoked'
      | 'SuccessRecorded'
      | 'Unpaused'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'FAILURE_THRESHOLD', values?: undefined): string;
  encodeFunctionData(functionFragment: 'FAILURE_WINDOW', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MAX_FAILURE_HISTORY', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MONITOR_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'RECOVERY_ATTEMPTS', values?: undefined): string;
  encodeFunctionData(functionFragment: 'TIMEOUT_PERIOD', values?: undefined): string;
  encodeFunctionData(functionFragment: 'circuitStates', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'closeCircuit', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'emergencyPause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'emergencyUnpause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'failureCounts', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'failureHistory',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'getCircuitStats', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'getFailureHistory', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'halfOpenSuccessCount', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'isCircuitClosed', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'lastFailureTime', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'lastSuccessTime', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'openCircuit', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
  encodeFunctionData(functionFragment: 'permanentShutdown', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'recordFailure',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'recordSuccess', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'triggerPermanentShutdown', values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'FAILURE_THRESHOLD', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'FAILURE_WINDOW', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MAX_FAILURE_HISTORY', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MONITOR_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'RECOVERY_ATTEMPTS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'TIMEOUT_PERIOD', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'circuitStates', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'closeCircuit', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyPause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyUnpause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'failureCounts', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'failureHistory', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getCircuitStats', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getFailureHistory', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'halfOpenSuccessCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isCircuitClosed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lastFailureTime', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lastSuccessTime', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'openCircuit', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'permanentShutdown', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'recordFailure', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'recordSuccess', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'triggerPermanentShutdown', data: BytesLike): Result;
}

export namespace CircuitClosedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CircuitHalfOpenedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CircuitOpenedEvent {
  export type InputTuple = [chainId: BigNumberish, failureCount: BigNumberish];
  export type OutputTuple = [chainId: bigint, failureCount: bigint];
  export interface OutputObject {
    chainId: bigint;
    failureCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnpausedEvent {
  export type InputTuple = [unpauser: AddressLike];
  export type OutputTuple = [unpauser: string];
  export interface OutputObject {
    unpauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FailureRecordedEvent {
  export type InputTuple = [reporter: AddressLike, chainId: BigNumberish];
  export type OutputTuple = [reporter: string, chainId: bigint];
  export interface OutputObject {
    reporter: string;
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
  export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuccessRecordedEvent {
  export type InputTuple = [reporter: AddressLike, chainId: BigNumberish];
  export type OutputTuple = [reporter: string, chainId: bigint];
  export interface OutputObject {
    reporter: string;
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CircuitBreaker extends BaseContract {
  connect(runner?: ContractRunner | null): CircuitBreaker;
  waitForDeployment(): Promise<this>;

  interface: CircuitBreakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], 'view'>;

  FAILURE_THRESHOLD: TypedContractMethod<[], [bigint], 'view'>;

  FAILURE_WINDOW: TypedContractMethod<[], [bigint], 'view'>;

  MAX_FAILURE_HISTORY: TypedContractMethod<[], [bigint], 'view'>;

  MONITOR_ROLE: TypedContractMethod<[], [string], 'view'>;

  OPERATOR_ROLE: TypedContractMethod<[], [string], 'view'>;

  RECOVERY_ATTEMPTS: TypedContractMethod<[], [bigint], 'view'>;

  TIMEOUT_PERIOD: TypedContractMethod<[], [bigint], 'view'>;

  circuitStates: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  closeCircuit: TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;

  emergencyPause: TypedContractMethod<[], [void], 'nonpayable'>;

  emergencyUnpause: TypedContractMethod<[], [void], 'nonpayable'>;

  failureCounts: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  failureHistory: TypedContractMethod<[arg0: BigNumberish, arg1: BigNumberish], [bigint], 'view'>;

  getCircuitStats: TypedContractMethod<
    [chainId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        state: bigint;
        failures: bigint;
        lastFailure: bigint;
        successCount: bigint;
        isShutdown: boolean;
      },
    ],
    'view'
  >;

  getFailureHistory: TypedContractMethod<[chainId: BigNumberish], [bigint[]], 'view'>;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], 'view'>;

  grantRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  halfOpenSuccessCount: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  hasRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;

  isCircuitClosed: TypedContractMethod<[chainId: BigNumberish], [boolean], 'nonpayable'>;

  lastFailureTime: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  lastSuccessTime: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  openCircuit: TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  paused: TypedContractMethod<[], [boolean], 'view'>;

  permanentShutdown: TypedContractMethod<[arg0: BigNumberish], [boolean], 'view'>;

  recordFailure: TypedContractMethod<
    [chainId: BigNumberish, failureSeverity: BigNumberish],
    [void],
    'nonpayable'
  >;

  recordSuccess: TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  renounceRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  revokeRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  supportsInterface: TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  triggerPermanentShutdown: TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'FAILURE_THRESHOLD'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'FAILURE_WINDOW'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MAX_FAILURE_HISTORY'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MONITOR_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'RECOVERY_ATTEMPTS'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'TIMEOUT_PERIOD'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'circuitStates'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'closeCircuit'
  ): TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'emergencyPause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'emergencyUnpause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'failureCounts'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'failureHistory'
  ): TypedContractMethod<[arg0: BigNumberish, arg1: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'getCircuitStats'
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        state: bigint;
        failures: bigint;
        lastFailure: bigint;
        successCount: bigint;
        isShutdown: boolean;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getFailureHistory'
  ): TypedContractMethod<[chainId: BigNumberish], [bigint[]], 'view'>;
  getFunction(
    nameOrSignature: 'getRoleAdmin'
  ): TypedContractMethod<[role: BytesLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'grantRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'halfOpenSuccessCount'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'hasRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isCircuitClosed'
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'lastFailureTime'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'lastSuccessTime'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'openCircuit'
  ): TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'paused'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'permanentShutdown'
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'recordFailure'
  ): TypedContractMethod<
    [chainId: BigNumberish, failureSeverity: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'recordSuccess'
  ): TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'renounceRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'revokeRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'supportsInterface'
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'triggerPermanentShutdown'
  ): TypedContractMethod<[chainId: BigNumberish], [void], 'nonpayable'>;

  getEvent(
    key: 'CircuitClosed'
  ): TypedContractEvent<
    CircuitClosedEvent.InputTuple,
    CircuitClosedEvent.OutputTuple,
    CircuitClosedEvent.OutputObject
  >;
  getEvent(
    key: 'CircuitHalfOpened'
  ): TypedContractEvent<
    CircuitHalfOpenedEvent.InputTuple,
    CircuitHalfOpenedEvent.OutputTuple,
    CircuitHalfOpenedEvent.OutputObject
  >;
  getEvent(
    key: 'CircuitOpened'
  ): TypedContractEvent<
    CircuitOpenedEvent.InputTuple,
    CircuitOpenedEvent.OutputTuple,
    CircuitOpenedEvent.OutputObject
  >;
  getEvent(
    key: 'EmergencyPaused'
  ): TypedContractEvent<
    EmergencyPausedEvent.InputTuple,
    EmergencyPausedEvent.OutputTuple,
    EmergencyPausedEvent.OutputObject
  >;
  getEvent(
    key: 'EmergencyUnpaused'
  ): TypedContractEvent<
    EmergencyUnpausedEvent.InputTuple,
    EmergencyUnpausedEvent.OutputTuple,
    EmergencyUnpausedEvent.OutputObject
  >;
  getEvent(
    key: 'FailureRecorded'
  ): TypedContractEvent<
    FailureRecordedEvent.InputTuple,
    FailureRecordedEvent.OutputTuple,
    FailureRecordedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'Paused'
  ): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
  getEvent(
    key: 'RoleAdminChanged'
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: 'RoleGranted'
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: 'RoleRevoked'
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: 'SuccessRecorded'
  ): TypedContractEvent<
    SuccessRecordedEvent.InputTuple,
    SuccessRecordedEvent.OutputTuple,
    SuccessRecordedEvent.OutputObject
  >;
  getEvent(
    key: 'Unpaused'
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    'CircuitClosed(uint256)': TypedContractEvent<
      CircuitClosedEvent.InputTuple,
      CircuitClosedEvent.OutputTuple,
      CircuitClosedEvent.OutputObject
    >;
    CircuitClosed: TypedContractEvent<
      CircuitClosedEvent.InputTuple,
      CircuitClosedEvent.OutputTuple,
      CircuitClosedEvent.OutputObject
    >;

    'CircuitHalfOpened(uint256)': TypedContractEvent<
      CircuitHalfOpenedEvent.InputTuple,
      CircuitHalfOpenedEvent.OutputTuple,
      CircuitHalfOpenedEvent.OutputObject
    >;
    CircuitHalfOpened: TypedContractEvent<
      CircuitHalfOpenedEvent.InputTuple,
      CircuitHalfOpenedEvent.OutputTuple,
      CircuitHalfOpenedEvent.OutputObject
    >;

    'CircuitOpened(uint256,uint256)': TypedContractEvent<
      CircuitOpenedEvent.InputTuple,
      CircuitOpenedEvent.OutputTuple,
      CircuitOpenedEvent.OutputObject
    >;
    CircuitOpened: TypedContractEvent<
      CircuitOpenedEvent.InputTuple,
      CircuitOpenedEvent.OutputTuple,
      CircuitOpenedEvent.OutputObject
    >;

    'EmergencyPaused(address)': TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;
    EmergencyPaused: TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;

    'EmergencyUnpaused(address)': TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;
    EmergencyUnpaused: TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;

    'FailureRecorded(address,uint256)': TypedContractEvent<
      FailureRecordedEvent.InputTuple,
      FailureRecordedEvent.OutputTuple,
      FailureRecordedEvent.OutputObject
    >;
    FailureRecorded: TypedContractEvent<
      FailureRecordedEvent.InputTuple,
      FailureRecordedEvent.OutputTuple,
      FailureRecordedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'Paused(address)': TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    'RoleGranted(bytes32,address,address)': TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    'RoleRevoked(bytes32,address,address)': TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    'SuccessRecorded(address,uint256)': TypedContractEvent<
      SuccessRecordedEvent.InputTuple,
      SuccessRecordedEvent.OutputTuple,
      SuccessRecordedEvent.OutputObject
    >;
    SuccessRecorded: TypedContractEvent<
      SuccessRecordedEvent.InputTuple,
      SuccessRecordedEvent.OutputTuple,
      SuccessRecordedEvent.OutputObject
    >;

    'Unpaused(address)': TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
