/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AetheronBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AetheronBridge__factory>
getContractFactory(name: 'CircuitBreaker', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CircuitBreaker__factory>
getContractFactory(name: 'RateLimiter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RateLimiter__factory>
getContractFactory(name: 'SentinelAMM', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelAMM__factory>
getContractFactory(name: 'SentinelCore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelCore__factory>
getContractFactory(name: 'SentinelCoreLoop', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelCoreLoop__factory>
getContractFactory(name: 'SentinelGovernance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelGovernance__factory>
getContractFactory(name: 'SentinelHomomorphicEncryption', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelHomomorphicEncryption__factory>
getContractFactory(name: 'SentinelInsuranceProtocol', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelInsuranceProtocol__factory>
getContractFactory(name: 'SentinelInterceptor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelInterceptor__factory>
getContractFactory(name: 'SentinelLiquidityMining', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelLiquidityMining__factory>
getContractFactory(name: 'IAetheronBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAetheronBridge__factory>
getContractFactory(name: 'ICircuitBreaker', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICircuitBreaker__factory>
getContractFactory(name: 'ISentinelInterceptor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISentinelInterceptor__factory>
getContractFactory(name: 'SentinelMonitor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelMonitor__factory>
getContractFactory(name: 'SentinelMultiSigVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelMultiSigVault__factory>
getContractFactory(name: 'SentinelOracleNetwork', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelOracleNetwork__factory>
getContractFactory(name: 'SentinelPredictiveThreatModel', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelPredictiveThreatModel__factory>
getContractFactory(name: 'SentinelQuantumGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelQuantumGuard__factory>
getContractFactory(name: 'SentinelQuantumKeyDistribution', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelQuantumKeyDistribution__factory>
getContractFactory(name: 'SentinelQuantumNeural', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelQuantumNeural__factory>
getContractFactory(name: 'SentinelReferralSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelReferralSystem__factory>
getContractFactory(name: 'SentinelRewardAggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelRewardAggregator__factory>
getContractFactory(name: 'SentinelSecurityAuditor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelSecurityAuditor__factory>
getContractFactory(name: 'SentinelSocialRecovery', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelSocialRecovery__factory>
getContractFactory(name: 'SentinelStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelStaking__factory>
getContractFactory(name: 'SentinelTimelock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelTimelock__factory>
getContractFactory(name: 'SentinelToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelToken__factory>
getContractFactory(name: 'SentinelYieldMaximizer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelYieldMaximizer__factory>
getContractFactory(name: 'SentinelZKIdentity', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelZKIdentity__factory>
getContractFactory(name: 'SentinelZKOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SentinelZKOracle__factory>
getContractFactory(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20Mock__factory>
getContractFactory(name: 'ERC20VotesMock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20VotesMock__factory>

  getContractAt(name: 'AetheronBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AetheronBridge>
getContractAt(name: 'CircuitBreaker', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CircuitBreaker>
getContractAt(name: 'RateLimiter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RateLimiter>
getContractAt(name: 'SentinelAMM', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelAMM>
getContractAt(name: 'SentinelCore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelCore>
getContractAt(name: 'SentinelCoreLoop', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelCoreLoop>
getContractAt(name: 'SentinelGovernance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelGovernance>
getContractAt(name: 'SentinelHomomorphicEncryption', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelHomomorphicEncryption>
getContractAt(name: 'SentinelInsuranceProtocol', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelInsuranceProtocol>
getContractAt(name: 'SentinelInterceptor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelInterceptor>
getContractAt(name: 'SentinelLiquidityMining', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelLiquidityMining>
getContractAt(name: 'IAetheronBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAetheronBridge>
getContractAt(name: 'ICircuitBreaker', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICircuitBreaker>
getContractAt(name: 'ISentinelInterceptor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISentinelInterceptor>
getContractAt(name: 'SentinelMonitor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelMonitor>
getContractAt(name: 'SentinelMultiSigVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelMultiSigVault>
getContractAt(name: 'SentinelOracleNetwork', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelOracleNetwork>
getContractAt(name: 'SentinelPredictiveThreatModel', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelPredictiveThreatModel>
getContractAt(name: 'SentinelQuantumGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelQuantumGuard>
getContractAt(name: 'SentinelQuantumKeyDistribution', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelQuantumKeyDistribution>
getContractAt(name: 'SentinelQuantumNeural', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelQuantumNeural>
getContractAt(name: 'SentinelReferralSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelReferralSystem>
getContractAt(name: 'SentinelRewardAggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelRewardAggregator>
getContractAt(name: 'SentinelSecurityAuditor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelSecurityAuditor>
getContractAt(name: 'SentinelSocialRecovery', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelSocialRecovery>
getContractAt(name: 'SentinelStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelStaking>
getContractAt(name: 'SentinelTimelock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelTimelock>
getContractAt(name: 'SentinelToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelToken>
getContractAt(name: 'SentinelYieldMaximizer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelYieldMaximizer>
getContractAt(name: 'SentinelZKIdentity', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelZKIdentity>
getContractAt(name: 'SentinelZKOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SentinelZKOracle>
getContractAt(name: 'ERC20Mock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20Mock>
getContractAt(name: 'ERC20VotesMock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20VotesMock>

  deployContract(name: 'AetheronBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AetheronBridge>
deployContract(name: 'CircuitBreaker', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CircuitBreaker>
deployContract(name: 'RateLimiter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RateLimiter>
deployContract(name: 'SentinelAMM', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelAMM>
deployContract(name: 'SentinelCore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelCore>
deployContract(name: 'SentinelCoreLoop', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelCoreLoop>
deployContract(name: 'SentinelGovernance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelGovernance>
deployContract(name: 'SentinelHomomorphicEncryption', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelHomomorphicEncryption>
deployContract(name: 'SentinelInsuranceProtocol', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelInsuranceProtocol>
deployContract(name: 'SentinelInterceptor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelInterceptor>
deployContract(name: 'SentinelLiquidityMining', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelLiquidityMining>
deployContract(name: 'IAetheronBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAetheronBridge>
deployContract(name: 'ICircuitBreaker', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICircuitBreaker>
deployContract(name: 'ISentinelInterceptor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISentinelInterceptor>
deployContract(name: 'SentinelMonitor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelMonitor>
deployContract(name: 'SentinelMultiSigVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelMultiSigVault>
deployContract(name: 'SentinelOracleNetwork', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelOracleNetwork>
deployContract(name: 'SentinelPredictiveThreatModel', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelPredictiveThreatModel>
deployContract(name: 'SentinelQuantumGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumGuard>
deployContract(name: 'SentinelQuantumKeyDistribution', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumKeyDistribution>
deployContract(name: 'SentinelQuantumNeural', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumNeural>
deployContract(name: 'SentinelReferralSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelReferralSystem>
deployContract(name: 'SentinelRewardAggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelRewardAggregator>
deployContract(name: 'SentinelSecurityAuditor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelSecurityAuditor>
deployContract(name: 'SentinelSocialRecovery', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelSocialRecovery>
deployContract(name: 'SentinelStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelStaking>
deployContract(name: 'SentinelTimelock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelTimelock>
deployContract(name: 'SentinelToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelToken>
deployContract(name: 'SentinelYieldMaximizer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelYieldMaximizer>
deployContract(name: 'SentinelZKIdentity', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelZKIdentity>
deployContract(name: 'SentinelZKOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelZKOracle>
deployContract(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'ERC20VotesMock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20VotesMock>

  deployContract(name: 'AetheronBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AetheronBridge>
deployContract(name: 'CircuitBreaker', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CircuitBreaker>
deployContract(name: 'RateLimiter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RateLimiter>
deployContract(name: 'SentinelAMM', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelAMM>
deployContract(name: 'SentinelCore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelCore>
deployContract(name: 'SentinelCoreLoop', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelCoreLoop>
deployContract(name: 'SentinelGovernance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelGovernance>
deployContract(name: 'SentinelHomomorphicEncryption', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelHomomorphicEncryption>
deployContract(name: 'SentinelInsuranceProtocol', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelInsuranceProtocol>
deployContract(name: 'SentinelInterceptor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelInterceptor>
deployContract(name: 'SentinelLiquidityMining', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelLiquidityMining>
deployContract(name: 'IAetheronBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAetheronBridge>
deployContract(name: 'ICircuitBreaker', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICircuitBreaker>
deployContract(name: 'ISentinelInterceptor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISentinelInterceptor>
deployContract(name: 'SentinelMonitor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelMonitor>
deployContract(name: 'SentinelMultiSigVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelMultiSigVault>
deployContract(name: 'SentinelOracleNetwork', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelOracleNetwork>
deployContract(name: 'SentinelPredictiveThreatModel', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelPredictiveThreatModel>
deployContract(name: 'SentinelQuantumGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumGuard>
deployContract(name: 'SentinelQuantumKeyDistribution', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumKeyDistribution>
deployContract(name: 'SentinelQuantumNeural', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelQuantumNeural>
deployContract(name: 'SentinelReferralSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelReferralSystem>
deployContract(name: 'SentinelRewardAggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelRewardAggregator>
deployContract(name: 'SentinelSecurityAuditor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelSecurityAuditor>
deployContract(name: 'SentinelSocialRecovery', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelSocialRecovery>
deployContract(name: 'SentinelStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelStaking>
deployContract(name: 'SentinelTimelock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelTimelock>
deployContract(name: 'SentinelToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelToken>
deployContract(name: 'SentinelYieldMaximizer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelYieldMaximizer>
deployContract(name: 'SentinelZKIdentity', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelZKIdentity>
deployContract(name: 'SentinelZKOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SentinelZKOracle>
deployContract(name: 'ERC20Mock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'ERC20VotesMock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20VotesMock>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  