/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RateLimiterInterface extends Interface {
    getFunction(nameOrSignature: "CALLER_ROLE" | "DEFAULT_ADMIN_ROLE" | "DEFAULT_RESET_PERIOD" | "MONITOR_ROLE" | "OPERATOR_ROLE" | "chainLimits" | "chainResetPeriods" | "currentUsage" | "emergencyPause" | "emergencyUnpause" | "getRoleAdmin" | "grantRole" | "hasRole" | "owner" | "paused" | "periodStart" | "processWithdrawal" | "renounceOwnership" | "renounceRole" | "resetUsage" | "revokeRole" | "setCaller" | "setChainLimit" | "setChainResetPeriod" | "supportsInterface" | "transferOwnership" | "updateRateLimit" | "withdrawals"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CallerUpdated" | "ChainLimitSet" | "ChainResetPeriodSet" | "EmergencyPaused" | "EmergencyUnpaused" | "OwnershipTransferred" | "Paused" | "RateLimitUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused" | "UsageReset" | "WithdrawalProcessed"): EventFragment;

    encodeFunctionData(functionFragment: 'CALLER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_RESET_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'MONITOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'chainLimits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'chainResetPeriods', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentUsage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyPause', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyUnpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'periodStart', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'processWithdrawal', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resetUsage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setCaller', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setChainLimit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setChainResetPeriod', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateRateLimit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawals', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'CALLER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_RESET_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MONITOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainResetPeriods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyUnpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'periodStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setChainLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setChainResetPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateRateLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawals', data: BytesLike): Result;
  }

  
    export namespace CallerUpdatedEvent {
      export type InputTuple = [caller: AddressLike, authorized: boolean];
      export type OutputTuple = [caller: string, authorized: boolean];
      export interface OutputObject {caller: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChainLimitSetEvent {
      export type InputTuple = [chainId: BigNumberish, limit: BigNumberish];
      export type OutputTuple = [chainId: bigint, limit: bigint];
      export interface OutputObject {chainId: bigint, limit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChainResetPeriodSetEvent {
      export type InputTuple = [chainId: BigNumberish, resetPeriod: BigNumberish];
      export type OutputTuple = [chainId: bigint, resetPeriod: bigint];
      export interface OutputObject {chainId: bigint, resetPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyPausedEvent {
      export type InputTuple = [pauser: AddressLike];
      export type OutputTuple = [pauser: string];
      export interface OutputObject {pauser: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyUnpausedEvent {
      export type InputTuple = [unpauser: AddressLike];
      export type OutputTuple = [unpauser: string];
      export interface OutputObject {unpauser: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RateLimitUpdatedEvent {
      export type InputTuple = [chainId: BigNumberish, oldLimit: BigNumberish, newLimit: BigNumberish];
      export type OutputTuple = [chainId: bigint, oldLimit: bigint, newLimit: bigint];
      export interface OutputObject {chainId: bigint, oldLimit: bigint, newLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsageResetEvent {
      export type InputTuple = [chainId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [chainId: bigint, timestamp: bigint];
      export interface OutputObject {chainId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalProcessedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, chainId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, chainId: bigint, timestamp: bigint];
      export interface OutputObject {user: string, amount: bigint, chainId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RateLimiter extends BaseContract {
    
    connect(runner?: ContractRunner | null): RateLimiter;
    waitForDeployment(): Promise<this>;

    interface: RateLimiterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALLER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_RESET_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MONITOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    chainLimits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    chainResetPeriods: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    currentUsage: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    emergencyPause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    emergencyUnpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    periodStart: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    processWithdrawal: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resetUsage: TypedContractMethod<
      [chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCaller: TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setChainLimit: TypedContractMethod<
      [chainId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setChainResetPeriod: TypedContractMethod<
      [chainId: BigNumberish, resetPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateRateLimit: TypedContractMethod<
      [chainId: BigNumberish, newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawals: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {user: string, amount: bigint, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALLER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_RESET_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MONITOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'chainLimits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'chainResetPeriods'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentUsage'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyPause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyUnpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'periodStart'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'processWithdrawal'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetUsage'): TypedContractMethod<
      [chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCaller'): TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setChainLimit'): TypedContractMethod<
      [chainId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setChainResetPeriod'): TypedContractMethod<
      [chainId: BigNumberish, resetPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateRateLimit'): TypedContractMethod<
      [chainId: BigNumberish, newLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawals'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {user: string, amount: bigint, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'CallerUpdated'): TypedContractEvent<CallerUpdatedEvent.InputTuple, CallerUpdatedEvent.OutputTuple, CallerUpdatedEvent.OutputObject>;
getEvent(key: 'ChainLimitSet'): TypedContractEvent<ChainLimitSetEvent.InputTuple, ChainLimitSetEvent.OutputTuple, ChainLimitSetEvent.OutputObject>;
getEvent(key: 'ChainResetPeriodSet'): TypedContractEvent<ChainResetPeriodSetEvent.InputTuple, ChainResetPeriodSetEvent.OutputTuple, ChainResetPeriodSetEvent.OutputObject>;
getEvent(key: 'EmergencyPaused'): TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
getEvent(key: 'EmergencyUnpaused'): TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RateLimitUpdated'): TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UsageReset'): TypedContractEvent<UsageResetEvent.InputTuple, UsageResetEvent.OutputTuple, UsageResetEvent.OutputObject>;
getEvent(key: 'WithdrawalProcessed'): TypedContractEvent<WithdrawalProcessedEvent.InputTuple, WithdrawalProcessedEvent.OutputTuple, WithdrawalProcessedEvent.OutputObject>;

    filters: {
      
      'CallerUpdated(address,bool)': TypedContractEvent<CallerUpdatedEvent.InputTuple, CallerUpdatedEvent.OutputTuple, CallerUpdatedEvent.OutputObject>;
      CallerUpdated: TypedContractEvent<CallerUpdatedEvent.InputTuple, CallerUpdatedEvent.OutputTuple, CallerUpdatedEvent.OutputObject>;
    

      'ChainLimitSet(uint256,uint256)': TypedContractEvent<ChainLimitSetEvent.InputTuple, ChainLimitSetEvent.OutputTuple, ChainLimitSetEvent.OutputObject>;
      ChainLimitSet: TypedContractEvent<ChainLimitSetEvent.InputTuple, ChainLimitSetEvent.OutputTuple, ChainLimitSetEvent.OutputObject>;
    

      'ChainResetPeriodSet(uint256,uint256)': TypedContractEvent<ChainResetPeriodSetEvent.InputTuple, ChainResetPeriodSetEvent.OutputTuple, ChainResetPeriodSetEvent.OutputObject>;
      ChainResetPeriodSet: TypedContractEvent<ChainResetPeriodSetEvent.InputTuple, ChainResetPeriodSetEvent.OutputTuple, ChainResetPeriodSetEvent.OutputObject>;
    

      'EmergencyPaused(address)': TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
      EmergencyPaused: TypedContractEvent<EmergencyPausedEvent.InputTuple, EmergencyPausedEvent.OutputTuple, EmergencyPausedEvent.OutputObject>;
    

      'EmergencyUnpaused(address)': TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
      EmergencyUnpaused: TypedContractEvent<EmergencyUnpausedEvent.InputTuple, EmergencyUnpausedEvent.OutputTuple, EmergencyUnpausedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RateLimitUpdated(uint256,uint256,uint256)': TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
      RateLimitUpdated: TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UsageReset(uint256,uint256)': TypedContractEvent<UsageResetEvent.InputTuple, UsageResetEvent.OutputTuple, UsageResetEvent.OutputObject>;
      UsageReset: TypedContractEvent<UsageResetEvent.InputTuple, UsageResetEvent.OutputTuple, UsageResetEvent.OutputObject>;
    

      'WithdrawalProcessed(address,uint256,uint256,uint256)': TypedContractEvent<WithdrawalProcessedEvent.InputTuple, WithdrawalProcessedEvent.OutputTuple, WithdrawalProcessedEvent.OutputObject>;
      WithdrawalProcessed: TypedContractEvent<WithdrawalProcessedEvent.InputTuple, WithdrawalProcessedEvent.OutputTuple, WithdrawalProcessedEvent.OutputObject>;
    
    };
  }