/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export interface SentinelInterceptorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'COOLDOWN_PERIOD'
      | 'DEFAULT_ADMIN_ROLE'
      | 'MAX_ANOMALIES_PER_BLOCK'
      | 'MONITOR_ROLE'
      | 'OPERATOR_ROLE'
      | 'addReporter'
      | 'anomalyCount'
      | 'anomalyFrequency'
      | 'anomalyThreshold'
      | 'authorizedReporters'
      | 'autonomousMode'
      | 'consecutiveAnomalies'
      | 'currentTVL'
      | 'detectAnomaly'
      | 'emergencyPause'
      | 'emergencyUnpause'
      | 'getAnomalyStats'
      | 'getRoleAdmin'
      | 'grantRole'
      | 'hasRole'
      | 'isAuthorizedReporter'
      | 'lastActionBlock'
      | 'lastAnomalyBlock'
      | 'owner'
      | 'paused'
      | 'removeReporter'
      | 'renounceOwnership'
      | 'renounceRole'
      | 'revokeRole'
      | 'supportsInterface'
      | 'thresholds'
      | 'toggleAutonomousMode'
      | 'transferOwnership'
      | 'tvlThreshold'
      | 'updateTVL'
      | 'updateThreshold'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'AnomalyDetected'
      | 'AutonomousModeToggled'
      | 'AutonomousPauseTriggered'
      | 'EmergencyPaused'
      | 'EmergencyUnpaused'
      | 'OwnershipTransferred'
      | 'Paused'
      | 'RoleAdminChanged'
      | 'RoleGranted'
      | 'RoleRevoked'
      | 'TVLUpdated'
      | 'ThresholdUpdated'
      | 'Unpaused'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'COOLDOWN_PERIOD', values?: undefined): string;
  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MAX_ANOMALIES_PER_BLOCK', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MONITOR_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'addReporter', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'anomalyCount', values?: undefined): string;
  encodeFunctionData(functionFragment: 'anomalyFrequency', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'anomalyThreshold', values?: undefined): string;
  encodeFunctionData(functionFragment: 'authorizedReporters', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'autonomousMode', values?: undefined): string;
  encodeFunctionData(functionFragment: 'consecutiveAnomalies', values?: undefined): string;
  encodeFunctionData(functionFragment: 'currentTVL', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'detectAnomaly',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'emergencyPause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'emergencyUnpause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getAnomalyStats', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'isAuthorizedReporter', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'lastActionBlock', values?: undefined): string;
  encodeFunctionData(functionFragment: 'lastAnomalyBlock', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
  encodeFunctionData(functionFragment: 'removeReporter', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'thresholds', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'toggleAutonomousMode', values: [boolean]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'tvlThreshold', values?: undefined): string;
  encodeFunctionData(functionFragment: 'updateTVL', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'updateThreshold',
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: 'COOLDOWN_PERIOD', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MAX_ANOMALIES_PER_BLOCK', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MONITOR_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addReporter', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'anomalyCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'anomalyFrequency', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'anomalyThreshold', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'authorizedReporters', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'autonomousMode', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'consecutiveAnomalies', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'currentTVL', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'detectAnomaly', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyPause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyUnpause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAnomalyStats', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isAuthorizedReporter', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lastActionBlock', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lastAnomalyBlock', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'removeReporter', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'thresholds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'toggleAutonomousMode', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'tvlThreshold', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateTVL', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateThreshold', data: BytesLike): Result;
}

export namespace AnomalyDetectedEvent {
  export type InputTuple = [
    anomalyType: BigNumberish,
    severity: BigNumberish,
    blockNumber: BigNumberish,
  ];
  export type OutputTuple = [anomalyType: bigint, severity: bigint, blockNumber: bigint];
  export interface OutputObject {
    anomalyType: bigint;
    severity: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutonomousModeToggledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutonomousPauseTriggeredEvent {
  export type InputTuple = [
    trigger: AddressLike,
    pauseDuration: BigNumberish,
    blockNumber: BigNumberish,
  ];
  export type OutputTuple = [trigger: string, pauseDuration: bigint, blockNumber: bigint];
  export interface OutputObject {
    trigger: string;
    pauseDuration: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnpausedEvent {
  export type InputTuple = [unpauser: AddressLike];
  export type OutputTuple = [unpauser: string];
  export interface OutputObject {
    unpauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
  export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TVLUpdatedEvent {
  export type InputTuple = [oldTVL: BigNumberish, newTVL: BigNumberish];
  export type OutputTuple = [oldTVL: bigint, newTVL: bigint];
  export interface OutputObject {
    oldTVL: bigint;
    newTVL: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    thresholdType: BigNumberish,
    oldValue: BigNumberish,
    newValue: BigNumberish,
  ];
  export type OutputTuple = [thresholdType: bigint, oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    thresholdType: bigint;
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelInterceptor extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelInterceptor;
  waitForDeployment(): Promise<this>;

  interface: SentinelInterceptorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  COOLDOWN_PERIOD: TypedContractMethod<[], [bigint], 'view'>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], 'view'>;

  MAX_ANOMALIES_PER_BLOCK: TypedContractMethod<[], [bigint], 'view'>;

  MONITOR_ROLE: TypedContractMethod<[], [string], 'view'>;

  OPERATOR_ROLE: TypedContractMethod<[], [string], 'view'>;

  addReporter: TypedContractMethod<[reporter: AddressLike], [void], 'nonpayable'>;

  anomalyCount: TypedContractMethod<[], [bigint], 'view'>;

  anomalyFrequency: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  anomalyThreshold: TypedContractMethod<[], [bigint], 'view'>;

  authorizedReporters: TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;

  autonomousMode: TypedContractMethod<[], [boolean], 'view'>;

  consecutiveAnomalies: TypedContractMethod<[], [bigint], 'view'>;

  currentTVL: TypedContractMethod<[], [bigint], 'view'>;

  detectAnomaly: TypedContractMethod<
    [anomalyType: BigNumberish, severity: BigNumberish],
    [void],
    'nonpayable'
  >;

  emergencyPause: TypedContractMethod<[], [void], 'nonpayable'>;

  emergencyUnpause: TypedContractMethod<[], [void], 'nonpayable'>;

  getAnomalyStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCount: bigint;
        lastBlock: bigint;
        consecutive: bigint;
        currentBlockFrequency: bigint;
      },
    ],
    'view'
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], 'view'>;

  grantRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  hasRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;

  isAuthorizedReporter: TypedContractMethod<[reporter: AddressLike], [boolean], 'view'>;

  lastActionBlock: TypedContractMethod<[], [bigint], 'view'>;

  lastAnomalyBlock: TypedContractMethod<[], [bigint], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  paused: TypedContractMethod<[], [boolean], 'view'>;

  removeReporter: TypedContractMethod<[reporter: AddressLike], [void], 'nonpayable'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  renounceRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  revokeRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;

  supportsInterface: TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;

  thresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;

  toggleAutonomousMode: TypedContractMethod<[enabled: boolean], [void], 'nonpayable'>;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  tvlThreshold: TypedContractMethod<[], [bigint], 'view'>;

  updateTVL: TypedContractMethod<[newTVL: BigNumberish], [void], 'nonpayable'>;

  updateThreshold: TypedContractMethod<
    [thresholdType: BigNumberish, newValue: BigNumberish],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'COOLDOWN_PERIOD'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_ANOMALIES_PER_BLOCK'
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MONITOR_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'addReporter'
  ): TypedContractMethod<[reporter: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'anomalyCount'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'anomalyFrequency'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(nameOrSignature: 'anomalyThreshold'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'authorizedReporters'
  ): TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;
  getFunction(nameOrSignature: 'autonomousMode'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(nameOrSignature: 'consecutiveAnomalies'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'currentTVL'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'detectAnomaly'
  ): TypedContractMethod<[anomalyType: BigNumberish, severity: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'emergencyPause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'emergencyUnpause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'getAnomalyStats'
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCount: bigint;
        lastBlock: bigint;
        consecutive: bigint;
        currentBlockFrequency: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getRoleAdmin'
  ): TypedContractMethod<[role: BytesLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'grantRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'hasRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isAuthorizedReporter'
  ): TypedContractMethod<[reporter: AddressLike], [boolean], 'view'>;
  getFunction(nameOrSignature: 'lastActionBlock'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'lastAnomalyBlock'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'paused'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'removeReporter'
  ): TypedContractMethod<[reporter: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'renounceRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'revokeRole'
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'supportsInterface'
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'thresholds'
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'toggleAutonomousMode'
  ): TypedContractMethod<[enabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'tvlThreshold'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'updateTVL'
  ): TypedContractMethod<[newTVL: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'updateThreshold'
  ): TypedContractMethod<
    [thresholdType: BigNumberish, newValue: BigNumberish],
    [void],
    'nonpayable'
  >;

  getEvent(
    key: 'AnomalyDetected'
  ): TypedContractEvent<
    AnomalyDetectedEvent.InputTuple,
    AnomalyDetectedEvent.OutputTuple,
    AnomalyDetectedEvent.OutputObject
  >;
  getEvent(
    key: 'AutonomousModeToggled'
  ): TypedContractEvent<
    AutonomousModeToggledEvent.InputTuple,
    AutonomousModeToggledEvent.OutputTuple,
    AutonomousModeToggledEvent.OutputObject
  >;
  getEvent(
    key: 'AutonomousPauseTriggered'
  ): TypedContractEvent<
    AutonomousPauseTriggeredEvent.InputTuple,
    AutonomousPauseTriggeredEvent.OutputTuple,
    AutonomousPauseTriggeredEvent.OutputObject
  >;
  getEvent(
    key: 'EmergencyPaused'
  ): TypedContractEvent<
    EmergencyPausedEvent.InputTuple,
    EmergencyPausedEvent.OutputTuple,
    EmergencyPausedEvent.OutputObject
  >;
  getEvent(
    key: 'EmergencyUnpaused'
  ): TypedContractEvent<
    EmergencyUnpausedEvent.InputTuple,
    EmergencyUnpausedEvent.OutputTuple,
    EmergencyUnpausedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'Paused'
  ): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
  getEvent(
    key: 'RoleAdminChanged'
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: 'RoleGranted'
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: 'RoleRevoked'
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: 'TVLUpdated'
  ): TypedContractEvent<
    TVLUpdatedEvent.InputTuple,
    TVLUpdatedEvent.OutputTuple,
    TVLUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'ThresholdUpdated'
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'Unpaused'
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    'AnomalyDetected(uint256,uint256,uint256)': TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;
    AnomalyDetected: TypedContractEvent<
      AnomalyDetectedEvent.InputTuple,
      AnomalyDetectedEvent.OutputTuple,
      AnomalyDetectedEvent.OutputObject
    >;

    'AutonomousModeToggled(bool)': TypedContractEvent<
      AutonomousModeToggledEvent.InputTuple,
      AutonomousModeToggledEvent.OutputTuple,
      AutonomousModeToggledEvent.OutputObject
    >;
    AutonomousModeToggled: TypedContractEvent<
      AutonomousModeToggledEvent.InputTuple,
      AutonomousModeToggledEvent.OutputTuple,
      AutonomousModeToggledEvent.OutputObject
    >;

    'AutonomousPauseTriggered(address,uint256,uint256)': TypedContractEvent<
      AutonomousPauseTriggeredEvent.InputTuple,
      AutonomousPauseTriggeredEvent.OutputTuple,
      AutonomousPauseTriggeredEvent.OutputObject
    >;
    AutonomousPauseTriggered: TypedContractEvent<
      AutonomousPauseTriggeredEvent.InputTuple,
      AutonomousPauseTriggeredEvent.OutputTuple,
      AutonomousPauseTriggeredEvent.OutputObject
    >;

    'EmergencyPaused(address)': TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;
    EmergencyPaused: TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;

    'EmergencyUnpaused(address)': TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;
    EmergencyUnpaused: TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'Paused(address)': TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    'RoleGranted(bytes32,address,address)': TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    'RoleRevoked(bytes32,address,address)': TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    'TVLUpdated(uint256,uint256)': TypedContractEvent<
      TVLUpdatedEvent.InputTuple,
      TVLUpdatedEvent.OutputTuple,
      TVLUpdatedEvent.OutputObject
    >;
    TVLUpdated: TypedContractEvent<
      TVLUpdatedEvent.InputTuple,
      TVLUpdatedEvent.OutputTuple,
      TVLUpdatedEvent.OutputObject
    >;

    'ThresholdUpdated(uint256,uint256,uint256)': TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    'Unpaused(address)': TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
