/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export declare namespace SentinelZKIdentity {
  export type ZKProofStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    inputs: BigNumberish[];
    publicInputsHash: BytesLike;
    verified: boolean;
    verificationTime: BigNumberish;
  };

  export type ZKProofStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    inputs: bigint[],
    publicInputsHash: string,
    verified: boolean,
    verificationTime: bigint,
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    inputs: bigint[];
    publicInputsHash: string;
    verified: boolean;
    verificationTime: bigint;
  };
}

export interface SentinelZKIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'CREDENTIAL_VALIDITY'
      | 'IDENTITY_EXPIRY'
      | 'MAX_TRUST_SCORE'
      | 'MIN_REPUTATION'
      | 'activeIdentities'
      | 'checkIdentityRequirements'
      | 'createZKIdentity'
      | 'credentialIssuers'
      | 'credentialToOwner'
      | 'getZKCredential'
      | 'getZKIdentity'
      | 'identities'
      | 'identityHashToOwner'
      | 'issueZKCredential'
      | 'owner'
      | 'proofs'
      | 'renounceOwnership'
      | 'revokeZKCredential'
      | 'submitZKProof'
      | 'transferOwnership'
      | 'verifiedCredentials'
      | 'verifyZKCredential'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'CredentialIssued'
      | 'IdentityCreated'
      | 'IdentityVerified'
      | 'OwnershipTransferred'
      | 'ZKProofVerified'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'CREDENTIAL_VALIDITY', values?: undefined): string;
  encodeFunctionData(functionFragment: 'IDENTITY_EXPIRY', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MAX_TRUST_SCORE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MIN_REPUTATION', values?: undefined): string;
  encodeFunctionData(functionFragment: 'activeIdentities', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'checkIdentityRequirements',
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'createZKIdentity', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'credentialIssuers', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'credentialToOwner', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'getZKCredential', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'getZKIdentity', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'identities', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'identityHashToOwner', values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: 'issueZKCredential',
    values: [BytesLike, string, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'proofs', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'revokeZKCredential', values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: 'submitZKProof',
    values: [SentinelZKIdentity.ZKProofStruct, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'verifiedCredentials', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'verifyZKCredential',
    values: [BytesLike, SentinelZKIdentity.ZKProofStruct]
  ): string;

  decodeFunctionResult(functionFragment: 'CREDENTIAL_VALIDITY', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'IDENTITY_EXPIRY', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MAX_TRUST_SCORE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MIN_REPUTATION', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'activeIdentities', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'checkIdentityRequirements', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createZKIdentity', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'credentialIssuers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'credentialToOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getZKCredential', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getZKIdentity', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'identities', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'identityHashToOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'issueZKCredential', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'proofs', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeZKCredential', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'submitZKProof', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verifiedCredentials', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verifyZKCredential', data: BytesLike): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [credentialId: BytesLike, identityId: BytesLike, credentialType: string];
  export type OutputTuple = [credentialId: string, identityId: string, credentialType: string];
  export interface OutputObject {
    credentialId: string;
    identityId: string;
    credentialType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityCreatedEvent {
  export type InputTuple = [user: AddressLike, identityHash: BytesLike];
  export type OutputTuple = [user: string, identityHash: string];
  export interface OutputObject {
    user: string;
    identityHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityVerifiedEvent {
  export type InputTuple = [identityHash: BytesLike, trustScore: BigNumberish];
  export type OutputTuple = [identityHash: string, trustScore: bigint];
  export interface OutputObject {
    identityHash: string;
    trustScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZKProofVerifiedEvent {
  export type InputTuple = [proofId: BytesLike, success: boolean];
  export type OutputTuple = [proofId: string, success: boolean];
  export interface OutputObject {
    proofId: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelZKIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelZKIdentity;
  waitForDeployment(): Promise<this>;

  interface: SentinelZKIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  CREDENTIAL_VALIDITY: TypedContractMethod<[], [bigint], 'view'>;

  IDENTITY_EXPIRY: TypedContractMethod<[], [bigint], 'view'>;

  MAX_TRUST_SCORE: TypedContractMethod<[], [bigint], 'view'>;

  MIN_REPUTATION: TypedContractMethod<[], [bigint], 'view'>;

  activeIdentities: TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;

  checkIdentityRequirements: TypedContractMethod<
    [user: AddressLike, minReputation: BigNumberish, minTrustScore: BigNumberish],
    [boolean],
    'view'
  >;

  createZKIdentity: TypedContractMethod<[publicKey: BytesLike], [string], 'nonpayable'>;

  credentialIssuers: TypedContractMethod<[arg0: BytesLike], [string], 'view'>;

  credentialToOwner: TypedContractMethod<[arg0: BytesLike], [string], 'view'>;

  getZKCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        credentialType: string;
        issuerId: string;
        issuanceTime: bigint;
        expirationTime: bigint;
        isValid: boolean;
        isRevoked: boolean;
      },
    ],
    'view'
  >;

  getZKIdentity: TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, boolean, bigint] & {
        identityHash: string;
        reputation: bigint;
        trustScore: bigint;
        isVerified: boolean;
        credentialCount: bigint;
      },
    ],
    'view'
  >;

  identities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean] & {
        identityHash: string;
        publicKey: string;
        reputation: bigint;
        trustScore: bigint;
        creationTime: bigint;
        isActive: boolean;
        isVerified: boolean;
      },
    ],
    'view'
  >;

  identityHashToOwner: TypedContractMethod<[arg0: BytesLike], [string], 'view'>;

  issueZKCredential: TypedContractMethod<
    [
      identityId: BytesLike,
      credentialType: string,
      attributes: BytesLike[],
      validityPeriod: BigNumberish,
    ],
    [string],
    'nonpayable'
  >;

  owner: TypedContractMethod<[], [string], 'view'>;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        publicInputsHash: string;
        verified: boolean;
        verificationTime: bigint;
      },
    ],
    'view'
  >;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  revokeZKCredential: TypedContractMethod<[credentialId: BytesLike], [void], 'nonpayable'>;

  submitZKProof: TypedContractMethod<
    [proof: SentinelZKIdentity.ZKProofStruct, publicInputsHash: BytesLike, proofType: string],
    [boolean],
    'nonpayable'
  >;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  verifiedCredentials: TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;

  verifyZKCredential: TypedContractMethod<
    [credentialId: BytesLike, presentationProof: SentinelZKIdentity.ZKProofStruct],
    [boolean],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'CREDENTIAL_VALIDITY'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'IDENTITY_EXPIRY'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MAX_TRUST_SCORE'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MIN_REPUTATION'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'activeIdentities'
  ): TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;
  getFunction(
    nameOrSignature: 'checkIdentityRequirements'
  ): TypedContractMethod<
    [user: AddressLike, minReputation: BigNumberish, minTrustScore: BigNumberish],
    [boolean],
    'view'
  >;
  getFunction(
    nameOrSignature: 'createZKIdentity'
  ): TypedContractMethod<[publicKey: BytesLike], [string], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'credentialIssuers'
  ): TypedContractMethod<[arg0: BytesLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'credentialToOwner'
  ): TypedContractMethod<[arg0: BytesLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'getZKCredential'
  ): TypedContractMethod<
    [credentialId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        credentialType: string;
        issuerId: string;
        issuanceTime: bigint;
        expirationTime: bigint;
        isValid: boolean;
        isRevoked: boolean;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getZKIdentity'
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, boolean, bigint] & {
        identityHash: string;
        reputation: bigint;
        trustScore: bigint;
        isVerified: boolean;
        credentialCount: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'identities'
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean] & {
        identityHash: string;
        publicKey: string;
        reputation: bigint;
        trustScore: bigint;
        creationTime: bigint;
        isActive: boolean;
        isVerified: boolean;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'identityHashToOwner'
  ): TypedContractMethod<[arg0: BytesLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'issueZKCredential'
  ): TypedContractMethod<
    [
      identityId: BytesLike,
      credentialType: string,
      attributes: BytesLike[],
      validityPeriod: BigNumberish,
    ],
    [string],
    'nonpayable'
  >;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'proofs'
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        publicInputsHash: string;
        verified: boolean;
        verificationTime: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'revokeZKCredential'
  ): TypedContractMethod<[credentialId: BytesLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'submitZKProof'
  ): TypedContractMethod<
    [proof: SentinelZKIdentity.ZKProofStruct, publicInputsHash: BytesLike, proofType: string],
    [boolean],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'verifiedCredentials'
  ): TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;
  getFunction(
    nameOrSignature: 'verifyZKCredential'
  ): TypedContractMethod<
    [credentialId: BytesLike, presentationProof: SentinelZKIdentity.ZKProofStruct],
    [boolean],
    'view'
  >;

  getEvent(
    key: 'CredentialIssued'
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: 'IdentityCreated'
  ): TypedContractEvent<
    IdentityCreatedEvent.InputTuple,
    IdentityCreatedEvent.OutputTuple,
    IdentityCreatedEvent.OutputObject
  >;
  getEvent(
    key: 'IdentityVerified'
  ): TypedContractEvent<
    IdentityVerifiedEvent.InputTuple,
    IdentityVerifiedEvent.OutputTuple,
    IdentityVerifiedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'ZKProofVerified'
  ): TypedContractEvent<
    ZKProofVerifiedEvent.InputTuple,
    ZKProofVerifiedEvent.OutputTuple,
    ZKProofVerifiedEvent.OutputObject
  >;

  filters: {
    'CredentialIssued(bytes32,bytes32,string)': TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    'IdentityCreated(address,bytes32)': TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;
    IdentityCreated: TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;

    'IdentityVerified(bytes32,uint256)': TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;
    IdentityVerified: TypedContractEvent<
      IdentityVerifiedEvent.InputTuple,
      IdentityVerifiedEvent.OutputTuple,
      IdentityVerifiedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'ZKProofVerified(bytes32,bool)': TypedContractEvent<
      ZKProofVerifiedEvent.InputTuple,
      ZKProofVerifiedEvent.OutputTuple,
      ZKProofVerifiedEvent.OutputObject
    >;
    ZKProofVerified: TypedContractEvent<
      ZKProofVerifiedEvent.InputTuple,
      ZKProofVerifiedEvent.OutputTuple,
      ZKProofVerifiedEvent.OutputObject
    >;
  };
}
