/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export declare namespace SentinelZKOracle {
  export type ZKProofStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    inputs: BigNumberish[];
  };

  export type ZKProofStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    inputs: bigint[],
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    inputs: bigint[];
  };
}

export interface SentinelZKOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MIN_STAKE'
      | 'SLASH_PERCENTAGE'
      | 'VERIFICATION_KEY'
      | 'activeFeeds'
      | 'createDataFeed'
      | 'dataFeeds'
      | 'getZKData'
      | 'oraclePublicKeys'
      | 'oracleStakes'
      | 'owner'
      | 'registerZKOracle'
      | 'renounceOwnership'
      | 'slashOracle'
      | 'submitZKProof'
      | 'transferOwnership'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'DataFeedCreated'
      | 'OracleSlashed'
      | 'OwnershipTransferred'
      | 'ZKProofSubmitted'
      | 'ZKProofVerified'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'MIN_STAKE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'SLASH_PERCENTAGE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'VERIFICATION_KEY', values?: undefined): string;
  encodeFunctionData(functionFragment: 'activeFeeds', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'createDataFeed', values: [string]): string;
  encodeFunctionData(functionFragment: 'dataFeeds', values: [string]): string;
  encodeFunctionData(functionFragment: 'getZKData', values: [string]): string;
  encodeFunctionData(functionFragment: 'oraclePublicKeys', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'oracleStakes', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'registerZKOracle', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'slashOracle',
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: 'submitZKProof',
    values: [string, BytesLike, BigNumberish, SentinelZKOracle.ZKProofStruct]
  ): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: 'MIN_STAKE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'SLASH_PERCENTAGE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'VERIFICATION_KEY', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'activeFeeds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createDataFeed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'dataFeeds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getZKData', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'oraclePublicKeys', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'oracleStakes', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'registerZKOracle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'slashOracle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'submitZKProof', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
}

export namespace DataFeedCreatedEvent {
  export type InputTuple = [feedName: string, creator: AddressLike];
  export type OutputTuple = [feedName: string, creator: string];
  export interface OutputObject {
    feedName: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleSlashedEvent {
  export type InputTuple = [oracle: AddressLike, amount: BigNumberish, reason: string];
  export type OutputTuple = [oracle: string, amount: bigint, reason: string];
  export interface OutputObject {
    oracle: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZKProofSubmittedEvent {
  export type InputTuple = [feedName: string, oracle: AddressLike, dataHash: BytesLike];
  export type OutputTuple = [feedName: string, oracle: string, dataHash: string];
  export interface OutputObject {
    feedName: string;
    oracle: string;
    dataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZKProofVerifiedEvent {
  export type InputTuple = [feedName: string, value: BigNumberish, confidence: BigNumberish];
  export type OutputTuple = [feedName: string, value: bigint, confidence: bigint];
  export interface OutputObject {
    feedName: string;
    value: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelZKOracle extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelZKOracle;
  waitForDeployment(): Promise<this>;

  interface: SentinelZKOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  MIN_STAKE: TypedContractMethod<[], [bigint], 'view'>;

  SLASH_PERCENTAGE: TypedContractMethod<[], [bigint], 'view'>;

  VERIFICATION_KEY: TypedContractMethod<[], [bigint], 'view'>;

  activeFeeds: TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;

  createDataFeed: TypedContractMethod<[feedName: string], [void], 'nonpayable'>;

  dataFeeds: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        feedName: string;
        latestDataHash: string;
        latestValue: bigint;
        lastUpdate: bigint;
        confidenceScore: bigint;
        isActive: boolean;
      },
    ],
    'view'
  >;

  getZKData: TypedContractMethod<
    [feedName: string],
    [
      [bigint, bigint, bigint, boolean] & {
        value: bigint;
        timestamp: bigint;
        confidence: bigint;
        isValid: boolean;
      },
    ],
    'view'
  >;

  oraclePublicKeys: TypedContractMethod<[arg0: AddressLike], [string], 'view'>;

  oracleStakes: TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  registerZKOracle: TypedContractMethod<[publicKey: BytesLike], [void], 'payable'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  slashOracle: TypedContractMethod<
    [oracle: AddressLike, amount: BigNumberish, reason: string],
    [void],
    'nonpayable'
  >;

  submitZKProof: TypedContractMethod<
    [
      feedName: string,
      dataHash: BytesLike,
      value: BigNumberish,
      proof: SentinelZKOracle.ZKProofStruct,
    ],
    [void],
    'payable'
  >;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'MIN_STAKE'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'SLASH_PERCENTAGE'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'VERIFICATION_KEY'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'activeFeeds'
  ): TypedContractMethod<[arg0: BigNumberish], [string], 'view'>;
  getFunction(
    nameOrSignature: 'createDataFeed'
  ): TypedContractMethod<[feedName: string], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'dataFeeds'): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        feedName: string;
        latestDataHash: string;
        latestValue: bigint;
        lastUpdate: bigint;
        confidenceScore: bigint;
        isActive: boolean;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'getZKData'): TypedContractMethod<
    [feedName: string],
    [
      [bigint, bigint, bigint, boolean] & {
        value: bigint;
        timestamp: bigint;
        confidence: bigint;
        isValid: boolean;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'oraclePublicKeys'
  ): TypedContractMethod<[arg0: AddressLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'oracleStakes'
  ): TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'registerZKOracle'
  ): TypedContractMethod<[publicKey: BytesLike], [void], 'payable'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'slashOracle'
  ): TypedContractMethod<
    [oracle: AddressLike, amount: BigNumberish, reason: string],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'submitZKProof'
  ): TypedContractMethod<
    [
      feedName: string,
      dataHash: BytesLike,
      value: BigNumberish,
      proof: SentinelZKOracle.ZKProofStruct,
    ],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getEvent(
    key: 'DataFeedCreated'
  ): TypedContractEvent<
    DataFeedCreatedEvent.InputTuple,
    DataFeedCreatedEvent.OutputTuple,
    DataFeedCreatedEvent.OutputObject
  >;
  getEvent(
    key: 'OracleSlashed'
  ): TypedContractEvent<
    OracleSlashedEvent.InputTuple,
    OracleSlashedEvent.OutputTuple,
    OracleSlashedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'ZKProofSubmitted'
  ): TypedContractEvent<
    ZKProofSubmittedEvent.InputTuple,
    ZKProofSubmittedEvent.OutputTuple,
    ZKProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: 'ZKProofVerified'
  ): TypedContractEvent<
    ZKProofVerifiedEvent.InputTuple,
    ZKProofVerifiedEvent.OutputTuple,
    ZKProofVerifiedEvent.OutputObject
  >;

  filters: {
    'DataFeedCreated(string,address)': TypedContractEvent<
      DataFeedCreatedEvent.InputTuple,
      DataFeedCreatedEvent.OutputTuple,
      DataFeedCreatedEvent.OutputObject
    >;
    DataFeedCreated: TypedContractEvent<
      DataFeedCreatedEvent.InputTuple,
      DataFeedCreatedEvent.OutputTuple,
      DataFeedCreatedEvent.OutputObject
    >;

    'OracleSlashed(address,uint256,string)': TypedContractEvent<
      OracleSlashedEvent.InputTuple,
      OracleSlashedEvent.OutputTuple,
      OracleSlashedEvent.OutputObject
    >;
    OracleSlashed: TypedContractEvent<
      OracleSlashedEvent.InputTuple,
      OracleSlashedEvent.OutputTuple,
      OracleSlashedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'ZKProofSubmitted(string,address,bytes32)': TypedContractEvent<
      ZKProofSubmittedEvent.InputTuple,
      ZKProofSubmittedEvent.OutputTuple,
      ZKProofSubmittedEvent.OutputObject
    >;
    ZKProofSubmitted: TypedContractEvent<
      ZKProofSubmittedEvent.InputTuple,
      ZKProofSubmittedEvent.OutputTuple,
      ZKProofSubmittedEvent.OutputObject
    >;

    'ZKProofVerified(string,uint256,uint256)': TypedContractEvent<
      ZKProofVerifiedEvent.InputTuple,
      ZKProofVerifiedEvent.OutputTuple,
      ZKProofVerifiedEvent.OutputObject
    >;
    ZKProofVerified: TypedContractEvent<
      ZKProofVerifiedEvent.InputTuple,
      ZKProofVerifiedEvent.OutputTuple,
      ZKProofVerifiedEvent.OutputObject
    >;
  };
}
