/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common.js';

export interface SentinelQuantumNeuralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MAX_LAYERS'
      | 'MAX_NEURONS'
      | 'PREDICTION_THRESHOLD'
      | 'QUANTUM_PRECISION'
      | 'addThreatSignature'
      | 'calibrateQuantumNeuralNetwork'
      | 'coherenceFactor'
      | 'entanglementStrength'
      | 'getNeuralArchitecture'
      | 'getPrediction'
      | 'neuralLayers'
      | 'neuralStability'
      | 'owner'
      | 'predictions'
      | 'processQuantumNeuralAnalysis'
      | 'quantumNoiseLevel'
      | 'renounceOwnership'
      | 'threatSignatures'
      | 'transferOwnership'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'NeuralNetworkUpdated'
      | 'NeuralPrediction'
      | 'OwnershipTransferred'
      | 'QuantumCalibrationPerformed'
      | 'ThreatSignatureDetected'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'MAX_LAYERS', values?: undefined): string;
  encodeFunctionData(functionFragment: 'MAX_NEURONS', values?: undefined): string;
  encodeFunctionData(functionFragment: 'PREDICTION_THRESHOLD', values?: undefined): string;
  encodeFunctionData(functionFragment: 'QUANTUM_PRECISION', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'addThreatSignature',
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'calibrateQuantumNeuralNetwork',
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'coherenceFactor', values?: undefined): string;
  encodeFunctionData(functionFragment: 'entanglementStrength', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getNeuralArchitecture', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPrediction', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'neuralLayers', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'neuralStability', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'predictions', values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: 'processQuantumNeuralAnalysis',
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: 'quantumNoiseLevel', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'threatSignatures', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: 'MAX_LAYERS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'MAX_NEURONS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'PREDICTION_THRESHOLD', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'QUANTUM_PRECISION', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addThreatSignature', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'calibrateQuantumNeuralNetwork', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'coherenceFactor', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'entanglementStrength', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getNeuralArchitecture', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPrediction', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'neuralLayers', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'neuralStability', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'predictions', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'processQuantumNeuralAnalysis', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'quantumNoiseLevel', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'threatSignatures', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
}

export namespace NeuralNetworkUpdatedEvent {
  export type InputTuple = [layers: BigNumberish, totalParameters: BigNumberish];
  export type OutputTuple = [layers: bigint, totalParameters: bigint];
  export interface OutputObject {
    layers: bigint;
    totalParameters: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NeuralPredictionEvent {
  export type InputTuple = [
    inputHash: BytesLike,
    threatLevel: BigNumberish,
    confidence: BigNumberish,
  ];
  export type OutputTuple = [inputHash: string, threatLevel: bigint, confidence: bigint];
  export interface OutputObject {
    inputHash: string;
    threatLevel: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuantumCalibrationPerformedEvent {
  export type InputTuple = [coherence: BigNumberish, stability: BigNumberish];
  export type OutputTuple = [coherence: bigint, stability: bigint];
  export interface OutputObject {
    coherence: bigint;
    stability: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatSignatureDetectedEvent {
  export type InputTuple = [patternHash: BytesLike, severity: BigNumberish];
  export type OutputTuple = [patternHash: string, severity: bigint];
  export interface OutputObject {
    patternHash: string;
    severity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelQuantumNeural extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelQuantumNeural;
  waitForDeployment(): Promise<this>;

  interface: SentinelQuantumNeuralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  MAX_LAYERS: TypedContractMethod<[], [bigint], 'view'>;

  MAX_NEURONS: TypedContractMethod<[], [bigint], 'view'>;

  PREDICTION_THRESHOLD: TypedContractMethod<[], [bigint], 'view'>;

  QUANTUM_PRECISION: TypedContractMethod<[], [bigint], 'view'>;

  addThreatSignature: TypedContractMethod<
    [patternData: BytesLike, severity: BigNumberish, metadata: BytesLike],
    [void],
    'nonpayable'
  >;

  calibrateQuantumNeuralNetwork: TypedContractMethod<
    [newCoherence: BigNumberish, newEntanglement: BigNumberish],
    [void],
    'nonpayable'
  >;

  coherenceFactor: TypedContractMethod<[], [bigint], 'view'>;

  entanglementStrength: TypedContractMethod<[], [bigint], 'view'>;

  getNeuralArchitecture: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        layers: bigint;
        totalNeurons: bigint;
        totalParameters: bigint;
        quantumCoherence: bigint;
      },
    ],
    'view'
  >;

  getPrediction: TypedContractMethod<
    [inputHash: BytesLike],
    [
      [bigint, bigint, string, bigint] & {
        threatProbability: bigint;
        confidenceLevel: bigint;
        predictionHash: string;
        timestamp: bigint;
      },
    ],
    'view'
  >;

  neuralLayers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        neurons: bigint;
        inputs: bigint;
        weightSeed: string;
        activation: bigint;
      },
    ],
    'view'
  >;

  neuralStability: TypedContractMethod<[], [bigint], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  predictions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, bigint, string] & {
        threatProbability: bigint;
        confidenceLevel: bigint;
        predictionHash: string;
        timestamp: bigint;
        predictor: string;
      },
    ],
    'view'
  >;

  processQuantumNeuralAnalysis: TypedContractMethod<
    [inputData: BigNumberish[]],
    [[bigint, bigint] & { threatLevel: bigint; confidence: bigint }],
    'nonpayable'
  >;

  quantumNoiseLevel: TypedContractMethod<[], [bigint], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  threatSignatures: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, string] & {
        patternHash: string;
        severity: bigint;
        frequency: bigint;
        lastDetected: bigint;
        active: boolean;
        metadata: string;
      },
    ],
    'view'
  >;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'MAX_LAYERS'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'MAX_NEURONS'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'PREDICTION_THRESHOLD'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'QUANTUM_PRECISION'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'addThreatSignature'
  ): TypedContractMethod<
    [patternData: BytesLike, severity: BigNumberish, metadata: BytesLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'calibrateQuantumNeuralNetwork'
  ): TypedContractMethod<
    [newCoherence: BigNumberish, newEntanglement: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(nameOrSignature: 'coherenceFactor'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'entanglementStrength'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'getNeuralArchitecture'): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        layers: bigint;
        totalNeurons: bigint;
        totalParameters: bigint;
        quantumCoherence: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'getPrediction'): TypedContractMethod<
    [inputHash: BytesLike],
    [
      [bigint, bigint, string, bigint] & {
        threatProbability: bigint;
        confidenceLevel: bigint;
        predictionHash: string;
        timestamp: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'neuralLayers'): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint] & {
        neurons: bigint;
        inputs: bigint;
        weightSeed: string;
        activation: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'neuralStability'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'predictions'): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, bigint, string] & {
        threatProbability: bigint;
        confidenceLevel: bigint;
        predictionHash: string;
        timestamp: bigint;
        predictor: string;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'processQuantumNeuralAnalysis'
  ): TypedContractMethod<
    [inputData: BigNumberish[]],
    [[bigint, bigint] & { threatLevel: bigint; confidence: bigint }],
    'nonpayable'
  >;
  getFunction(nameOrSignature: 'quantumNoiseLevel'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'threatSignatures'): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean, string] & {
        patternHash: string;
        severity: bigint;
        frequency: bigint;
        lastDetected: bigint;
        active: boolean;
        metadata: string;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  getEvent(
    key: 'NeuralNetworkUpdated'
  ): TypedContractEvent<
    NeuralNetworkUpdatedEvent.InputTuple,
    NeuralNetworkUpdatedEvent.OutputTuple,
    NeuralNetworkUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'NeuralPrediction'
  ): TypedContractEvent<
    NeuralPredictionEvent.InputTuple,
    NeuralPredictionEvent.OutputTuple,
    NeuralPredictionEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'QuantumCalibrationPerformed'
  ): TypedContractEvent<
    QuantumCalibrationPerformedEvent.InputTuple,
    QuantumCalibrationPerformedEvent.OutputTuple,
    QuantumCalibrationPerformedEvent.OutputObject
  >;
  getEvent(
    key: 'ThreatSignatureDetected'
  ): TypedContractEvent<
    ThreatSignatureDetectedEvent.InputTuple,
    ThreatSignatureDetectedEvent.OutputTuple,
    ThreatSignatureDetectedEvent.OutputObject
  >;

  filters: {
    'NeuralNetworkUpdated(uint256,uint256)': TypedContractEvent<
      NeuralNetworkUpdatedEvent.InputTuple,
      NeuralNetworkUpdatedEvent.OutputTuple,
      NeuralNetworkUpdatedEvent.OutputObject
    >;
    NeuralNetworkUpdated: TypedContractEvent<
      NeuralNetworkUpdatedEvent.InputTuple,
      NeuralNetworkUpdatedEvent.OutputTuple,
      NeuralNetworkUpdatedEvent.OutputObject
    >;

    'NeuralPrediction(bytes32,uint256,uint256)': TypedContractEvent<
      NeuralPredictionEvent.InputTuple,
      NeuralPredictionEvent.OutputTuple,
      NeuralPredictionEvent.OutputObject
    >;
    NeuralPrediction: TypedContractEvent<
      NeuralPredictionEvent.InputTuple,
      NeuralPredictionEvent.OutputTuple,
      NeuralPredictionEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'QuantumCalibrationPerformed(uint256,uint256)': TypedContractEvent<
      QuantumCalibrationPerformedEvent.InputTuple,
      QuantumCalibrationPerformedEvent.OutputTuple,
      QuantumCalibrationPerformedEvent.OutputObject
    >;
    QuantumCalibrationPerformed: TypedContractEvent<
      QuantumCalibrationPerformedEvent.InputTuple,
      QuantumCalibrationPerformedEvent.OutputTuple,
      QuantumCalibrationPerformedEvent.OutputObject
    >;

    'ThreatSignatureDetected(bytes32,uint256)': TypedContractEvent<
      ThreatSignatureDetectedEvent.InputTuple,
      ThreatSignatureDetectedEvent.OutputTuple,
      ThreatSignatureDetectedEvent.OutputObject
    >;
    ThreatSignatureDetected: TypedContractEvent<
      ThreatSignatureDetectedEvent.InputTuple,
      ThreatSignatureDetectedEvent.OutputTuple,
      ThreatSignatureDetectedEvent.OutputObject
    >;
  };
}
