/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace SentinelMonitor {
      
    export type SystemHealthStruct = {sentinelAnomalies: BigNumberish, bridgeTVL: BigNumberish, activeCircuits: BigNumberish, totalTransfers: BigNumberish, overallHealth: boolean, lastUpdate: BigNumberish}

    export type SystemHealthStructOutput = [sentinelAnomalies: bigint, bridgeTVL: bigint, activeCircuits: bigint, totalTransfers: bigint, overallHealth: boolean, lastUpdate: bigint] & {sentinelAnomalies: bigint, bridgeTVL: bigint, activeCircuits: bigint, totalTransfers: bigint, overallHealth: boolean, lastUpdate: bigint }
  
    }

  export interface SentinelMonitorInterface extends Interface {
    getFunction(nameOrSignature: "addTrackedChain" | "alertConditions" | "authorizeContract" | "authorizedContracts" | "getSystemHealth" | "isCriticalState" | "owner" | "renounceOwnership" | "setAlertCondition" | "systemHealth" | "trackedChainIds" | "transferOwnership" | "updateHealth"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AlertConditionSet" | "AlertTriggered" | "ContractAuthorized" | "HealthUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addTrackedChain', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'alertConditions', values: [string]): string;
encodeFunctionData(functionFragment: 'authorizeContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedContracts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSystemHealth', values?: undefined): string;
encodeFunctionData(functionFragment: 'isCriticalState', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAlertCondition', values: [string, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'systemHealth', values?: undefined): string;
encodeFunctionData(functionFragment: 'trackedChainIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateHealth', values: [AddressLike, AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addTrackedChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'alertConditions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSystemHealth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCriticalState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAlertCondition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'systemHealth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trackedChainIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateHealth', data: BytesLike): Result;
  }

  
    export namespace AlertConditionSetEvent {
      export type InputTuple = [conditionId: string, threshold: BigNumberish, severity: BigNumberish];
      export type OutputTuple = [conditionId: string, threshold: bigint, severity: bigint];
      export interface OutputObject {conditionId: string, threshold: bigint, severity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AlertTriggeredEvent {
      export type InputTuple = [conditionId: string, severity: BigNumberish, message: string];
      export type OutputTuple = [conditionId: string, severity: bigint, message: string];
      export interface OutputObject {conditionId: string, severity: bigint, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContractAuthorizedEvent {
      export type InputTuple = [contractAddress: AddressLike];
      export type OutputTuple = [contractAddress: string];
      export interface OutputObject {contractAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HealthUpdatedEvent {
      export type InputTuple = [health: SentinelMonitor.SystemHealthStruct];
      export type OutputTuple = [health: SentinelMonitor.SystemHealthStructOutput];
      export interface OutputObject {health: SentinelMonitor.SystemHealthStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SentinelMonitor extends BaseContract {
    
    connect(runner?: ContractRunner | null): SentinelMonitor;
    waitForDeployment(): Promise<this>;

    interface: SentinelMonitorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addTrackedChain: TypedContractMethod<
      [chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    alertConditions: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, boolean, bigint] & {description: string, threshold: bigint, active: boolean, severity: bigint }],
      'view'
    >
    

    
    authorizeContract: TypedContractMethod<
      [contractAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedContracts: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getSystemHealth: TypedContractMethod<
      [],
      [SentinelMonitor.SystemHealthStructOutput],
      'view'
    >
    

    
    isCriticalState: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAlertCondition: TypedContractMethod<
      [conditionId: string, threshold: BigNumberish, severity: BigNumberish, description: string, ],
      [void],
      'nonpayable'
    >
    

    
    systemHealth: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, bigint] & {sentinelAnomalies: bigint, bridgeTVL: bigint, activeCircuits: bigint, totalTransfers: bigint, overallHealth: boolean, lastUpdate: bigint }],
      'view'
    >
    

    
    trackedChainIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateHealth: TypedContractMethod<
      [sentinelContract: AddressLike, bridgeContract: AddressLike, circuitBreakerContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addTrackedChain'): TypedContractMethod<
      [chainId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'alertConditions'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, boolean, bigint] & {description: string, threshold: bigint, active: boolean, severity: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'authorizeContract'): TypedContractMethod<
      [contractAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedContracts'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getSystemHealth'): TypedContractMethod<
      [],
      [SentinelMonitor.SystemHealthStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isCriticalState'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAlertCondition'): TypedContractMethod<
      [conditionId: string, threshold: BigNumberish, severity: BigNumberish, description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'systemHealth'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, bigint] & {sentinelAnomalies: bigint, bridgeTVL: bigint, activeCircuits: bigint, totalTransfers: bigint, overallHealth: boolean, lastUpdate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'trackedChainIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateHealth'): TypedContractMethod<
      [sentinelContract: AddressLike, bridgeContract: AddressLike, circuitBreakerContract: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AlertConditionSet'): TypedContractEvent<AlertConditionSetEvent.InputTuple, AlertConditionSetEvent.OutputTuple, AlertConditionSetEvent.OutputObject>;
getEvent(key: 'AlertTriggered'): TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
getEvent(key: 'ContractAuthorized'): TypedContractEvent<ContractAuthorizedEvent.InputTuple, ContractAuthorizedEvent.OutputTuple, ContractAuthorizedEvent.OutputObject>;
getEvent(key: 'HealthUpdated'): TypedContractEvent<HealthUpdatedEvent.InputTuple, HealthUpdatedEvent.OutputTuple, HealthUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AlertConditionSet(string,uint256,uint256)': TypedContractEvent<AlertConditionSetEvent.InputTuple, AlertConditionSetEvent.OutputTuple, AlertConditionSetEvent.OutputObject>;
      AlertConditionSet: TypedContractEvent<AlertConditionSetEvent.InputTuple, AlertConditionSetEvent.OutputTuple, AlertConditionSetEvent.OutputObject>;
    

      'AlertTriggered(string,uint256,string)': TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
      AlertTriggered: TypedContractEvent<AlertTriggeredEvent.InputTuple, AlertTriggeredEvent.OutputTuple, AlertTriggeredEvent.OutputObject>;
    

      'ContractAuthorized(address)': TypedContractEvent<ContractAuthorizedEvent.InputTuple, ContractAuthorizedEvent.OutputTuple, ContractAuthorizedEvent.OutputObject>;
      ContractAuthorized: TypedContractEvent<ContractAuthorizedEvent.InputTuple, ContractAuthorizedEvent.OutputTuple, ContractAuthorizedEvent.OutputObject>;
    

      'HealthUpdated(tuple)': TypedContractEvent<HealthUpdatedEvent.InputTuple, HealthUpdatedEvent.OutputTuple, HealthUpdatedEvent.OutputObject>;
      HealthUpdated: TypedContractEvent<HealthUpdatedEvent.InputTuple, HealthUpdatedEvent.OutputTuple, HealthUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }