name: Deploy to Staging / Production

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run compile
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Deploy
        run: npx hardhat run scripts/add-liquidity.js --network ${{ github.ref == 'refs/heads/main' && 'mainnet' || 'sepolia' }} --config hardhat.config.cjs
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          BASE_MAINNET_RPC_URL: ${{ secrets.RPC_URL }}
          BASE_TESTNET_RPC_URL: ${{ secrets.RPC_URL }}
